---
title: "DESeq2_explained"
format: html
---

```{r}
library(tidyverse)
library(ggbeeswarm)
library(ggreveal)
```

```{r}
sig_summary <- read_csv("../../output/06_deg/spawnnight/sig_summary.csv")
norm_130_df <- read_csv("../../output/06_deg/spawnnight/norm_130_df.csv")
metadata <- read_csv("../../metadata/metadata_or.csv")
```

```{r}
top_gene <- sig_summary %>% 
  arrange(desc(log2FoldChange)) %>% 
  slice(1) %>% 
  pull(gene_id)
```

```{r}
plot_top <- norm_130_df %>% 
  dplyr::filter(gene_id == top_gene) %>% 
  pivot_longer(cols = 2:last_col(), names_to = "sample_id") %>% 
  left_join(metadata)%>% 
  mutate(
    hpf = factor(hpf, levels = c(4, 9, 14)),
    leachate = factor(leachate, levels = c("control", "low", "mid", "high"))
  )

plot_sum <- plot_top %>% 
  group_by(group, hpf, stage, leachate) %>% 
  summarize(mean_expr = mean(value)) %>% 
  mutate(
    hpf = factor(hpf, levels = c(4, 9, 14)),
    leachate = factor(leachate, levels = c("control", "low", "mid", "high")),
    stage = factor(stage, levels = c("cleavage", "prawnchip", "earlygastrula"))
  )
```
```{r}
theme_sleek_axe <- function() {
  theme_sleek() +
    theme(
      panel.border = element_rect(
        color = "grey70",
        fill = NA,
        linewidth = 0.5
      ),
      axis.line.x  = element_line(color = "grey70"),
      axis.line.y  = element_line(color = "grey70"),
      
      plot.title = element_text(
        size  = 12,
        color = "grey30",
        hjust = 0.5,
        margin = margin(b = 20)
      ),
      
      strip.text = element_text(size = 10, color = "grey30"),
      
      plot.subtitle = element_text(
        size   = 10,
        color  = "grey30",
        hjust  = 0.5,
        margin = margin(b = 40)
      ),
      
      axis.title = element_text(size = 10, color = "grey30"),
      axis.text = element_text(size = 10, color = "grey30"),
      legend.title = element_text(size = 10, color = "grey30"),
      legend.text = element_text(size = 10, color = "grey30")
    )
}


theme_pptx <- function() {
  theme_sleek() +
    theme(
      panel.border = element_blank(),
      axis.line.x  = element_line(color = "grey70"),
      axis.line.y  = element_line(color = "grey70"),
      
      plot.title = element_text(
        size  = 40,
        color = "grey30",
        hjust = 0.5,
        margin = margin(b = 20)
      ),
      
      strip.text = element_text(size = 24, color = "grey30"),
      
      plot.subtitle = element_text(
        size   = 24,
        color  = "grey30",
        hjust  = 0.5,
        margin = margin(b = 40)
      ),
      
      axis.title = element_text(size = 24, color = "grey30"),
      axis.text = element_text(size = 24, color = "grey30"),
      legend.title = element_text(size = 24, color = "grey30"),
      legend.text = element_text(size = 24, color = "grey30")
    )
}

```

## Geoms
```{r}
geom_defaults <- function() {
  update_geom_defaults("point",      list(size = 1.5, stroke = 0.5))
  update_geom_defaults("line",       list(linewidth = 0.5))
  update_geom_defaults("boxplot",    list(linewidth = 0.5))
  update_geom_defaults("violin",     list(linewidth = 0.5))
  update_geom_defaults("vline",      list(linewidth = 0.5))
  update_geom_defaults("hline",      list(linewidth = 0.5))
  update_geom_defaults("abline",     list(linewidth = 0.5))
  update_geom_defaults("errorbar",   list(linewidth = 0.5))
  update_geom_defaults("pointrange", list(linewidth = 0.5))
  update_geom_defaults("crossbar",   list(linewidth = 0.5))
  update_geom_defaults("linerange",  list(linewidth = 0.5))
  update_geom_defaults("path", list(linewidth = 0.5))
  update_geom_defaults("segment", list(linewidth = 0.5))
  update_geom_defaults("text", list(size = 3))
}

geom_pptx <- function() {
  update_geom_defaults("point",   list(size = 5, stroke = 1.2))
  update_geom_defaults("line",    list(linewidth = 1.5))
  update_geom_defaults("boxplot", list(linewidth = 1.2))
  update_geom_defaults("violin",  list(linewidth = 1.2))
  update_geom_defaults("vline", list(linewidth = 1.5))
  update_geom_defaults("hline", list(linewidth = 1.5))
  update_geom_defaults("abline", list(linewidth = 1.5))
  update_geom_defaults("errorbar", list(linewidth = 1.5))
  update_geom_defaults("pointrange", list(linewidth = 1.5))
  update_geom_defaults("crossbar", list(linewidth = 1.5))
  update_geom_defaults("linerange", list(linewidth = 1.5))
  update_geom_defaults("path", list(linewidth = 1.5))
  update_geom_defaults("segment", list(linewidth = 1.5))
  update_geom_defaults("text", list(size = 7))
}

```



## Set colorschemes

```{r}
leachate.colors <- c(control = "#5ABDAC", 
                low = "#BBC7FF",
                mid = "#7D8BFF", 
                high = "#592F7D")

stage.5.colors <- c(
  egg           = "#FFE066",
  cleavage      = "#FFBA08",
  morula        = "#F48C06",
  prawnchip     = "#DC2F02",
  earlygastrula = "#6A040F"
  )

stage.3.colors <- c(
  cleavage      = "#FFBA08",
  prawnchip     = "#DC2F02",
  earlygastrula = "#6A040F"
  )

night.colors <- c(July_6th = "#21918C", 
                  July_7th = "#578B21", 
                  July_8th = "#1E2440")

status.colors <- c(typical   = "#75C165", 
                   uncertain = "#E3FAA5", 
                   malformed = "#8B0069")
```

```{r}
ggplot(plot_sum, aes(x=leachate, y=mean_expr, fill=leachate)) + 
  geom_point(shape=21, size=5, color="grey20")+
  labs(
    y = "Log2 Normalized Gene Expression",
    x = ""
  ) +
  scale_fill_manual(values=leachate.colors) +
  theme_sleek_axe()+
  theme(
    panel.grid.major=element_line(color="grey70"),
    panel.grid.minor=element_line(color="grey70")
  )
```

```{r}
ggplot(plot_sum, aes(x=leachate, y=mean_expr, fill=stage)) + 
  geom_point(shape=21, size=5, color="grey20")+
  labs(
    y = "Log2 Normalized Gene Expression",
    x = ""
  ) +
  guides(fill = guide_legend(reverse = TRUE)) +
  #geom_hline(yintercept=41.49945, linetype="dashed", color="grey20") +
  scale_fill_manual(values=stage.3.colors) +
  theme_sleek_axe()+
  theme(
    panel.grid.major=element_line(color="grey70"),
    panel.grid.minor=element_line(color="grey70")
  )
```
```{r fig.width=16, fig.height=9}
geom_pptx()
p_stage <- ggplot(
  plot_sum,
  aes(
    x = leachate,
    y = mean_expr,
    #fill = stage,
    color=stage,
    group = stage
  )
) + 
  geom_point(shape = 16, size = 10) +
  #scale_fill_manual(values = stage.3.colors) +
  scale_color_manual(values = stage.3.colors) +
  guides(color=guide_legend(reverse=TRUE))+
  labs(
    y = "Log2 Normalized Gene Expression",
    x = ""
  ) +
  theme_pptx()+
  theme(
    panel.grid.major=element_line(color="grey70"),
    panel.grid.minor=element_line(color="grey70")
  )

stage_reveal <- reveal_groups(
  p_stage,
  order = c(1,2,3,4)
)

stage_reveal
```
```{r}
for(i in seq_along(stage_reveal)) {

  ggsave(
    filename = paste0("../../figs/reveal_", i, ".png"),
    plot = stage_reveal[[i]],
    width = 16,
    height = 9,
    dpi = 600
  )

}
```



```{r}
ggsave(
  "../../figs/deg_ex.png",
  width=8,
  height = 4.5,
  dpi = 900
)
```



```{r}
library(ggreveal)
```


```{r}

```


# log2fold change

```{r}
ggplot(sig_summary, aes(x=log2FoldChange, y=list, color=list)) + 
  geom_point()
```

